version: '3'
services:
  nest:
    container_name: nest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    volumes:
      - /svr/app
      - /svr/app/node_modules
    ports:
      - '${PORT}:${PORT}'
